pipeline {
    agent any
    environment {
        IMAGE_NAME = 'cart-service'
        AWS_REGION = 'us-east-1'
        ECR_REPO = 'cart-service-repo'
        ACCOUNT_ID = 'your-aws-account-id'
    }
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/YOUR_GITHUB_REPO/cart-service.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    docker build -t $IMAGE_NAME .
                    docker tag $IMAGE_NAME:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                    docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                '''
            }
        }
        stage('Deploy to EKS') {
            steps {
                sh 'kubectl apply -f k8s/cart-deployment.yaml'
            }
        }
    }
}
